template: "Hello, %s"

logging:
  level: INFO

  loggers:
    "com.mwaltman.devops": DEBUG

  appenders:
    - type: console
      discardingThreshold: 0
      timeZone: UTC
      logFormat: "%d{HH:mm:ss.SSS [%thread] %-5level %logger{36} - %msg%n"
      target: stderr
    - type: file
      currentLogFilename: ./../logs/dropwizard.log
      archivedLogFilenamePattern: ./../logs/dropwizard-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC
# Keep a newline with no whitespace at the end of this file because we tack
# another config on the end of this one via merging two input streams
