version: '3.7'
services:
  artifactory:
    build:
      context: .
      dockerfile: docker/Dockerfile.artifactory
    ports:
      - 8083:8081
    volumes:
      - ./vdata/persistent/artifactory/access:/artifactory/access
      - ./vdata/persistent/artifactory/backup:/artifactory/backup
      - ./vdata/persistent/artifactory/data:/artifactory/data
      - ./vdata/persistent/artifactory/etc:/artifactory/etc
      - ./vdata/persistent/artifactory/logs:/artifactory/logs
  etcd:
    build:
      context: .
      dockerfile: docker/Dockerfile.etcd
    ports:
      - 2379:2379
    volumes:
      - ./config:/config
  jenkins:
    build:
      context: .
      dockerfile: docker/Dockerfile.jenkins
    init: true
    ports:
      - 8084:8080
      - 50000:50000
    volumes:
      - ./vdata/persistent/jenkins:/var/jenkins_home
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
  resque:
    build:
      context: .
      dockerfile: docker/Dockerfile.resque
    links:
      - redis
    ports:
      - 5678:5678
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    links:
      - etcd
    ports:
      - 5006:5006
      - 8080:8080
      - 8081:8081
    tmpfs:
      - /devops/core/build
      - /devops/data/build
      - /devops/framework/build
      - /devops/web/build
    volumes:
      - .:/devops
      - ./vdata/persistent/monitor/web/logs:/devops/logs
      - ./vdata/persistent/monitor/web/gradle:/devops/.gradle
      - ./vdata/persistent/monitor/web/gradle/root:/root/.gradle
