version: '3.7'
services:
  artifactory:
    build:
      context: .
      dockerfile: docker/Dockerfile.artifactory
    ports:
      - 8081:8081
    volumes:
      - ./vdata/persistent/artifactory/access:/artifactory/access
      - ./vdata/persistent/artifactory/backup:/artifactory/backup
      - ./vdata/persistent/artifactory/data:/artifactory/data
      - ./vdata/persistent/artifactory/etc:/artifactory/etc
      - ./vdata/persistent/artifactory/logs:/artifactory/logs
  etcd:
    build:
      context: .
      dockerfile: docker/Dockerfile.etcd
    ports:
      - 2379:2379
    volumes:
      - ./config:/config
  jenkins:
    build:
      context: .
      dockerfile: docker/Dockerfile.jenkins
    init: true
    ports:
      - 8082:8080
      - 50000:50000
    volumes:
      - ./vdata/persistent/jenkins:/var/jenkins_home
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
  resque:
    build:
      context: .
      dockerfile: docker/Dockerfile.resque
    links:
      - redis
    ports:
      - 5678:5678
